[workspace]
members = ["bootloader", "runtime", "ksupport", "satman"]
resolver = "2"

[profile.dev]
incremental = false # incompatible with LTO
lto = true
debug = 2

[patch.crates-io]
proc-macro2 = { git = "https://github.com/airwoodix/proc-macro2", branch="is-available-nightly-unstable" }
