name: Build software
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - aqt
jobs:
  build:
    name: Build software
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - name: Build AQT tester software
        run: |
          nix build .#artiq-software-aqt-tester
      - name: Store build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aqt-tester-software
          path: |
            result/runtime.elf
            result/runtime.fbi
